#!/opt/local/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Time::Local;
use POSIX qw(strftime);
use JSON "decode_json";

my $cmd = "/usr/bin/rrdtool update /home/pi/Metoffice/weather.rrd --template Wind_Speed:Temperature:Dew_Point:Humidity";

# suck in the JSON on stdin
my $json = <STDIN>;

# translate the JSON into a multi-level perl structure
my $hash = decode_json($json);

my $days = $hash->{SiteRep}->{DV}->{Location}->{Period};
while (my $day = shift @$days) {
	$day->{value} =~ s/-|Z//g;
	my $timepoints = $day->{Rep};
	while (my $m = shift @$timepoints) {
		$cmd .= sprintf(" '%02d:00 %s'@%d:%.1f:%.1f:%.1f", $m->{'$'}/60, $day->{value}, 
								   $m->{S}, $m->{T}, $m->{Dp}, $m->{H});
	}
}
print $cmd . "\n";
